#!/usr/bin/php
<?php
if (!isset($argv[1]) || $argv[1] == 'help' || $argv[1] == '--help' || $argv[1] == '-h')
	die("Usage: phpquery URL --method1 arg1 arg2 argN --method2 arg1 arg2 argN ...
Example: phpquery 'http://localhost' --find 'div > p' --contents
Docs: http://code.google.com/p/phpquery/wiki/LibrarySections\n");
set_include_path(get_include_path()
	.':'.'/usr/lib/phpquery'
	.':'.realpath(dirname(__FILE__).'/../phpQuery')
);
require_once('phpQuery.php');
//phpQuery::$debug = true;
//var_dump($argv);
if (parse_url($argv[1], PHP_URL_HOST)) {
	phpQuery::ajaxAllowURL($argv[1]);
	phpQuery::get($argv[1], 'czx023gcs9sg83');
} else {
	czx023gcs9sg83($argv[1]);
}
function czx023gcs9sg83($html) {
	global $argv;
	$pq = phpQuery::newDocument($html);
	$method = null;
	$params = array();
	foreach(array_slice($argv, 2) as $param) {
		if (strpos($param, '--') === 0) {
			if ($method) {
				$pq = call_user_func_array(array($pq, $method), $params);
			}
			$method = substr($param, 2);	// delete --
			$params = array();
		} else {
			$params[] = strtolower($param) == 'null'
				? null
				: $param;
		}
	}
	if ($method)
		$pq = call_user_func_array(array($pq, $method), $params);
	print trim($pq)."\n";
}
?>
